# Generated by Django 3.1.1 on 2020-10-12 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=11)),
                ('profilepicture', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songtitle', models.CharField(max_length=100)),
                ('songImage', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('genre', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('dateRelease', models.DateField()),
                ('producer', models.CharField(max_length=100)),
                ('songwriter', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Song',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='melody.customer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song', to='melody.song')),
            ],
            options={
                'db_table': 'Playlist',
            },
        ),
    ]
