# Generated by Django 3.1.1 on 2020-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
