# Generated by Django 3.1.1 on 2020-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songImage',
        ),
        migrations.AddField(
            model_name='customer',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilepicture',
            field=models.ImageField(blank=True, default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
