# Generated by Django 3.1.1 on 2020-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0002_auto_20201012_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songImage',
        ),
    ]
