# Generated by Django 3.1.1 on 2020-10-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0003_remove_song_songimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
