# Generated by Django 3.1.1 on 2020-10-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0004_auto_20201014_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
